[build]
  publish = "static-analytics"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/@sparticuz/chromium/**/*"]
  external_node_modules = ["@sparticuz/chromium"]
  
[functions.getAnalyticsData]
  timeout = 60

[functions.getAnalyticsData-new]
  timeout = 30

[functions.sample_data_provider]
  timeout = 30

[dev]
  publish = "static-analytics"
  functions = "netlify/functions"
  
# Rewrite all API paths to the appropriate functions
[[redirects]]
  from = "/api/analytics"
  to = "/.netlify/functions/getAnalyticsData-new"
  status = 200
  force = true

[[redirects]]
  from = "/api/getAnalyticsData"
  to = "/.netlify/functions/getAnalyticsData-new"
  status = 200
  force = true

[[redirects]]
  from = "/api/sample-data"
  to = "/.netlify/functions/sample_data_provider"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 