[build]
  publish = "static-analytics"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["puppeteer-core"]
  
[functions.sample_data_provider]
  timeout = 30

[dev]
  publish = "static-analytics"
  functions = "netlify/functions"
  
# Rewrite all API paths to the appropriate functions
[[redirects]]
  from = "/api/analytics"
  to = "/.netlify/functions/sample_data_provider"
  status = 200
  force = true

[[redirects]]
  from = "/api/getAnalyticsData"
  to = "/.netlify/functions/sample_data_provider"
  status = 200
  force = true

[[redirects]]
  from = "/api/sample-data"
  to = "/.netlify/functions/sample_data_provider"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 